# shared beamline values for all services

ioc-instance:
  securityContext:
    runAsUser: 37988
    runAsGroup: 37988

  dataVolume:
    pvc: false
    hostPath: /dls/p45/data

  useAffinity: true

  # extra toleration for bl45p's nodetype taint
  tolerations:
    - key: "nodetype"
      operator: "Equal"
      value: "test-rig"
      effect: "NoSchedule"

global:
  beamline: bl45p
