beamline: bl45p
namespace: epics-iocs
base_image: ghcr.io/epics-containers/ioc-adaravis:2.2.1r1.1

# root folder of generic ioc source - not expected to change
iocFolder: /epics/ioc

# useAffinity - only run on nodes with label beamline:bl45p
useAffinity: true
# resource limits
memory: 2048Mi
cpu: 4
